# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='Content', max_length=32),
        ),
    ]
